FROM maven:3-jdk-8-openj9 AS builder

COPY src /usr/src/app/src  
COPY pom.xml /usr/src/app

RUN mvn -f /usr/src/app/pom.xml clean \
    && mvn -f /usr/src/app/pom.xml compile \
    && mvn -f /usr/src/app/pom.xml package

FROM adoptopenjdk/openjdk8-openj9:alpine-jre AS runner

RUN apk add gnupg tar curl

# curl -fsSL 'https://www.apache.org/dist/tomee/KEYS' | awk -F ' = ' '$1 ~ /^ +Key fingerprint$/ { gsub(" ", "", $2); print $2 }' | sort -u
ENV GPG_KEYS \
    223D3A74B068ECA354DC385CE126833F9CF64915 \
    678F2D98F1FD9643811639FB622B8F2D043F71D8 \
    7A2744A8A9AAF063C23EB7868EBE7DBE8D050EEF \
    82D8419BA697F0E7FB85916EE91287822FDB81B1 \
    9056B710F1E332780DE7AF34CBAEBE39A46C4CA1 \
    A57DAF81C1B69921F4BA8723A8DE0A4DB863A7C1 \
    B7574789F5018690043E6DD9C212662E12F3E1DD \
    B8B301E6105DF628076BD92C5483E55897ABD9B9 \
    BDD0BBEB753192957EFC5F896A62FC8EF17D8FEF \
    C23A3F6F595EBD0F960270CC997C8F1A5BE6E4C1 \
    D11DF12CC2CA4894BDE638B967C1227A2678363C \
    DBCCD103B8B24F86FFAAB025C8BB472CD297D428 \
    F067B8140F5DD80E1D3B5D92318242FE9A0B1183 \
    FAA603D58B1BA4EDF65896D0ED340E0E6D545F97
    
RUN set -xe \
    && for key in $GPG_KEYS; do \
        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
    done

WORKDIR /app

RUN set -x \
        && curl -fSL https://repo.maven.apache.org/maven2/org/apache/tomee/apache-tomee/7.1.0/apache-tomee-7.1.0-webprofile.tar.gz.asc -o tomee.tar.gz.asc \
        && curl -fSL https://repo.maven.apache.org/maven2/org/apache/tomee/apache-tomee/7.1.0/apache-tomee-7.1.0-webprofile.tar.gz -o tomee.tar.gz \
        && gpg --batch --verify tomee.tar.gz.asc tomee.tar.gz \
        && tar -zxf tomee.tar.gz \
        && mv apache-tomee-webprofile-7.1.0/* /app \
        && rm -Rf apache-tomee-webprofile-7.1.0 \
        && rm tomee.tar.gz* 

RUN rm -Rf /app/webapps/*

COPY --from=builder /usr/src/app/target/GestionTiendas.war /app/webapps/ROOT.war

RUN sed 's/FINEST/WARNING/g' -i /app/conf/logging.properties
RUN sed 's/FINE/WARNING/g' -i /app/conf/logging.properties

VOLUME ["/app/logs"]

EXPOSE 8080
CMD ["/app/bin/catalina.sh", "run"]