name: Build Mauro Desktop & Server
on: [push]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Go to Server Project Folder
      run: cd ./src/Server
    - name: Clean with Maven
      run: mvn clean --file pom.xml
    - name: Compile with Maven
      run: mvn compile --file pom.xml
    - name: Package with Maven
      run: mvn package --file pom.xml
  build-desktop:
    runs-on: windows-latest
    env:
      Solution_Path: src\Desktop\MauzoDesktop.sln
      Test_Project_Path: src\Desktop\Desktop\MauzoDesktop.csproj
      Wpf_Project_Path: src\Desktop\Desktop\MauzoDesktop.csproj
    steps:
    - uses: actions/checkout@v2
      name: Checkout the Source Code
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build the Windows Application Packaging Project (wapproj) 
      run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle
      env:
        AppxBundle: Never
        BuildMode: SideLoadOnly
        Configuration: Release
        TargetPlatform: x64